export const BASSSTAT = [
    {
        id: 0,
        bassid: 0,
        heading: 'Model:',
        text: '7 String bliss'
    },
    {
        id: 1,
        bassid: 0,
        heading: 'Model:',
        text: 'Taasdfasdf',

    },
    {
        id: 2,
        bassid: 0,
        heading: 'Model:',
        text: 'asdfasdfasdf',

    },
    {
        id: 3,
        bassid: 0,
        heading: 'Model:',
        text: "asdfasdf",

    },
    {
        id: 4,
        bassid: 0,
        heading: 'Model:',
        text: "Tasdfsadfasdfa."
    },
    {
        id: 5,
        bassid: 1,
        heading: 'Model:',
        text: "asdfasdfasdf"
    },
    {
        id: 6,
        bassid: 1,
        heading: 'Model:',
        text: 'asdfasdfa'
    },
    {
        id: 7,
        bassid: 1,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 8,
        bassid: 1,
        heading: 'Model:',
        text: "Text filler"
    },
    {
        id: 9,
        bassid: 1,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 10,
        bassid: 2,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 11,
        bassid: 2,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 12,
        bassid: 2,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 13,
        bassid: 2,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 14,
        bassid: 2,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 15,
        bassid: 3,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 16,
        bassid: 3,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 17,
        bassid: 3,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 18,
        bassid: 3,
        heading: 'Model:',
        text: 'Text filler'
    },
    {
        id: 19,
        bassid: 3,
        heading: 'Model:',
        text: "TText filler"
    }
];
