export const BASSSTAT = [
    {
        id: 0,
        bassid: 0,
        heading: 'Model:',
        text: '7 String bliss'
    },
    {
        id: 1,
        bassid: 0,
        heading: 'Model:',
        text: 'This lone monkey kept following us back to our tent.',

    },
    {
        id: 2,
        bassid: 0,
        heading: 'Model:',
        text: 'Do not feed the wildlife. They will follow you back to the tent.',

    },
    {
        id: 3,
        bassid: 0,
        heading: 'Model:',
        text: "Avoid Sundays; couldn't relax and play my flute with all the noisy kids.",

    },
    {
        id: 4,
        bassid: 0,
        heading: 'Model:',
        text: "This has been our favorite campsite for over 7 years. It is an absolutely beautiful site. The hosts are very friendly and helpful. Don't forget to try out the lake."
    },
    {
        id: 5,
        bassid: 1,
        heading: 'Model:',
        text: "There's nothing more fun than setting up a tent in a rainstorm."
    },
    {
        id: 6,
        bassid: 1,
        heading: 'Model:',
        text: 'I caught a world-record-breaking trout here on my last visit.'
    },
    {
        id: 7,
        bassid: 1,
        heading: 'Model:',
        text: 'The campground was beautiful, but the bugs could bite sometimes.'
    },
    {
        id: 8,
        bassid: 1,
        heading: 'Model:',
        text: "Love the river but I didn't catch any fish."
    },
    {
        id: 9,
        bassid: 1,
        heading: 'Model:',
        text: 'A wonderful place to reconnect with nature.'
    },
    {
        id: 10,
        bassid: 2,
        heading: 'Model:',
        text: 'The Frozen Tundra is great place for family and friends camping!'
    },
    {
        id: 11,
        bassid: 2,
        heading: 'Model:',
        text: 'We had to leave about 2am to go back to the city because the quiet was just too much!'
    },
    {
        id: 12,
        bassid: 2,
        heading: 'Model:',
        text: 'The stars at night were a revelation!'
    },
    {
        id: 13,
        bassid: 2,
        heading: 'Model:',
        text: 'Great scenic hiking trails but it was challenging to go up the mountain.'
    },
    {
        id: 14,
        bassid: 2,
        heading: 'Model:',
        text: 'Perfect scenery for a smoked kipper breakfast with friends!'
    },
    {
        id: 15,
        bassid: 3,
        heading: 'Model:',
        text: 'Just remember a bear can run and climb faster than you...'
    },
    {
        id: 16,
        bassid: 3,
        heading: 'Model:',
        text: 'Excellent site to recharge from the city.'
    },
    {
        id: 17,
        bassid: 3,
        heading: 'Model:',
        text: 'What a magnificent view!'
    },
    {
        id: 18,
        bassid: 3,
        heading: 'Model:',
        text: 'The sites are huge! We felt like we were in the middle of nowhere, in a good way.'
    },
    {
        id: 19,
        bassid: 3,
        heading: 'Model:',
        text: "The photos don't do justice to the beauty of this place."
    }
];
